services:
  backend:
    build: ./Backend
    ports:
      - "5001:3001"
    env_file:
      - ./Backend/.env

  frontend:
    build:
      context: ./Frontend
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_CLOUDFLARE_SITE_KEY=${VITE_CLOUDFLARE_SITE_KEY}
    env_file:
      - ./Frontend/.env
    ports:
      - "80:80"
    depends_on:
      - backend
